CREATE TABLE orders (
	id serial PRIMARY KEY,
  chainid SMALLINT NOT NULL,
  swapcontract VARCHAR (42) NOT NULL,
  nonce BIGINT NOT NULL,
  expiry BIGINT NOT NULL,
  protocolFee SMALLINT NOT NULL,
  signerwallet VARCHAR (42) NOT NULL,
  signertoken VARCHAR (42) NOT NULL,
  signerkind VARCHAR (10) NOT NULL,
  signerid BIGINT NOT NULL,
  senderwallet VARCHAR (42) NOT NULL,
  sendertoken VARCHAR (42) NOT NULL,
  senderkind VARCHAR (10) NOT NULL,
  senderamount BIGINT NOT NULL,
  affiliatewallet VARCHAR (42) NOT NULL,
  affiliateamount BIGINT NOT NULL,
  v SMALLINT NOT NULL,
  r VARCHAR (66),
  s VARCHAR (66)
);
